### ISSUE TITLE
rev_list broken with utf-8 commit message (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by sotarok** [mojombo/grit#109]
I use grit (version 3fc864f3c637) with gitlabhq and I got hit with a problem.

Log (this is rails log):

```
Started GET "/xxxx/commits" for 183.177.156.109 at 2012-04-21 03:15:27 +0900
Processing by CommitsController#index as HTML
  Parameters: {"project_id"=>"xxxx"}
  ...
Completed 500 Internal Server Error in 1029ms

Encoding::CompatibilityError (incompatible character encodings: UTF-8 and ASCII-8BIT):
  app/models/commit.rb:72:in `commits'
  app/models/project/repository_trait.rb:27:in `commits'
  app/controllers/commits_controller.rb:18:in `index'
```

So I traced this problem and I found it on `lib/grit/git-ruby/repository.rb` of `grit`.

```
320         if options[:pretty] == 'raw'
321           log.map {|k, v| v }.join('')
322         else
323           log.map {|k, v| k }.join("\n")
324         end
```

I tried to fix this problem with following patch:

```
--- repository.rb       2012-04-21 03:27:21.000000000 +0900
+++ repository_fixed.rb 2012-04-21 03:27:55.000000000 +0900
@@ -318,7 +318,7 @@
         end

         if options[:pretty] == 'raw'
-          log.map {|k, v| v }.join('')
+          log.map {|k, v| v.force_encoding('utf-8') }.join('')
         else
           log.map {|k, v| k }.join("\n")
         end
```

I can't judge is it right to fix the problem but gitlab worked completely with this patch.
Thank you for your attention to this patch.

**Comment by arr2036** [comment]
+1

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
