### ISSUE TITLE
Grit crashes when dealing with files that have accented characters in them

### ISSUE THREAD

**Issue by nickserv** [mojombo/grit#139]
Error when deploying files with [Dandelion](https://github.com/scttnlsn/dandelion), which uses Grit:

```
~/Repos/folder_of_site_to_deploy master ✔ ➜ dandelion deploy
Connecting to [hidden]
Remote revision:      ---
Deploying revision:  [hidden]
[a lot of successful file transfers]
Uploading file: "a_bunch_of_directories/Cap\303\255tulo 5A vocabulary notes 2.doc"
/home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/lib/dandelion/git.rb:67:in `show': undefined method `data' for nil:NilClass (NoMethodError)
    from /home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/lib/dandelion/deployment.rb:140:in `block in deploy'
    from /home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/lib/dandelion/deployment.rb:135:in `each'
    from /home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/lib/dandelion/deployment.rb:135:in `deploy'
    from /home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/lib/dandelion/command/deploy.rb:50:in `execute'
    from /home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/lib/dandelion/application.rb:38:in `block in execute'
    from /home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/lib/dandelion/command.rb:80:in `initialize'
    from /home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/lib/dandelion/application.rb:36:in `new'
    from /home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/lib/dandelion/application.rb:36:in `execute'
    from /home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/lib/dandelion/application.rb:7:in `execute'
    from /home/nicolas/.gem/ruby/1.9.1/gems/dandelion-0.3.7/bin/dandelion:7:in `<top (required)>'
    from /home/nicolas/.gem/ruby/1.9.1/bin/dandelion:23:in `load'
    from /home/nicolas/.gem/ruby/1.9.1/bin/dandelion:23:in `<main>'
```

Filename of first problem file: `Capítulo 5A vocabulary notes 2.doc`

I'm guessing this is an issue with the accented i.

See https://github.com/scttnlsn/dandelion/issues/12 for the issue I reported to Dandelion's issue tracker.

**Comment by nickserv** [comment]
Comment from @scttnlsn on the Dandelion issue:

> Looks like Grit (https://github.com/mojombo/grit) is not finding the name in the Git tree object: https://github.com/mojombo/grit/blob/master/lib/grit/tree.rb#L96
> 
> I presume this is because the file is not being read with UTF8 encoding. Perhaps an issue should be opened for Grit.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
