### ISSUE TITLE
Exception raised when checking out a specific commit

### ISSUE THREAD

**Issue by duncan-bayne** [mojombo/grit#166]
I'm trying to check out a specific commit by SHA, using Grit:

```
Dir.mktmpdir do |tmp_dir|
  git = Grit::Git.new('')
  git.clone({ quiet: true, progress: false }, git_url, tmp_dir)
  git.checkout(git_sha)
end
```

The clone works, but the checkout fails:

```
/home/duncan/.rvm/gems/ruby-1.9.3-p392/gems/grit-2.5.0/lib/grit/git.rb:319:in `delete': can't convert Symbol into String (TypeError)
    from /home/duncan/.rvm/gems/ruby-1.9.3-p392/gems/grit-2.5.0/lib/grit/git.rb:319:in `native'
    from /home/duncan/.rvm/gems/ruby-1.9.3-p392/gems/grit-2.5.0/lib/grit/git.rb:372:in `method_missing'
    from /home/duncan/biq-eb-deploy/lib/build.rb:8:in `block (2 levels) in artifact_zip_from_git'
    from /home/duncan/biq-eb-deploy/lib/build.rb:6:in `chdir'
    from /home/duncan/biq-eb-deploy/lib/build.rb:6:in `block in artifact_zip_from_git'
    from /home/duncan/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
    from /home/duncan/biq-eb-deploy/lib/build.rb:2:in `artifact_zip_from_git'
    from ./biq-eb-deploy:53:in `<main>'
```

**Comment by reneflottweg63** [comment]
nice

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
