### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by graaff** [mojombo/grit#88]
I'm getting the following test failures with current HEAD (a9dbc43a2f8b82ce7698fa118466177a2929e45e):

```
  1) Failure:
test_patch_id(TestCommit)
    [./test/test_commit.rb:200:in `test_patch_id'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.10/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:22:in `__send__'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.10/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:22:in `run']:
<"9450b04e4f83ad0067199c9e9e338197d1835cbb"> expected but was
<"99f7025a1817044c5ce053f310eb8abc81338c6f">.

  2) Failure:
test_logs_stderr(TestGit) [./test/test_git.rb:19]:
not all expectations were satisfied
unsatisfied expectations:
- expected exactly once, not yet invoked: Grit.log(includes('git: 'bad' is not a git command'))
satisfied expectations:
- allowed any number of times, already invoked 3 times: Grit.log(any_parameters)

  3) Failure:
test_logs_stderr_when_skipping_timeout(TestGit) [./test/test_git.rb:26]:
not all expectations were satisfied
unsatisfied expectations:
- expected exactly once, not yet invoked: Grit.log(includes('git: 'bad' is not a git command'))
satisfied expectations:
- allowed any number of times, already invoked 3 times: Grit.log(any_parameters)

  4) Failure:
test_native_process_info_option_on_failure(TestGit)
    [./test/test_git.rb:127:in `test_native_process_info_option_on_failure'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.10/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:22:in `__send__'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.10/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:22:in `run']:
<1> expected but was
<255>.
```

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
