### ISSUE TITLE
raise NoSuchPath when ls_tree_path gets a nil tree

### ISSUE THREAD

**Issue by rtomayko** [mojombo/grit#9]
We're getting a bunch of `NoMethodError`s when someone hits non sensical URLs like: `http://github.com/chregu/planet-php/blob/2c3126329d11cdfca31faca0ed87a8aef888e096/inc/config-admin.php.dist/dbase.php`. Here, `config-admin.php.dist` is a blob so `ls_tree_path` gets back a `nil` tree but doesn't check for it.

Backtrace:

```
NoMethodError: private method `split' called for nil:NilClass
/data/github/current/ernie/../vendor/gems/grit/lib/grit/git-ruby/repository.rb:223:in `ls_tree_path'
/data/github/current/ernie/../vendor/gems/grit/lib/grit/git-ruby/repository.rb:230:in `ls_tree_path'
/data/github/current/ernie/../vendor/gems/grit/lib/grit/git-ruby/repository.rb:177:in `ls_tree'
/data/github/current/ernie/../vendor/gems/grit/lib/grit/git-ruby/repository.rb:176:in `each'
/data/github/current/ernie/../vendor/gems/grit/lib/grit/git-ruby/repository.rb:176:in `ls_tree'
/data/github/current/ernie/../vendor/gems/grit/lib/grit/git-ruby.rb:36:in `ls_tree'
/data/github/current/ernie/smoke.rb:67:in `send'
/data/github/current/ernie/smoke.rb:67:in `rpc'
/data/github/current/ernie/smoke.rb:110
/var/lib/gems/1.8/gems/ernie-1.3.0/lib/ernie.rb:79:in `call'
/var/lib/gems/1.8/gems/ernie-1.3.0/lib/ernie.rb:79:in `dispatch'
/var/lib/gems/1.8/gems/ernie-1.3.0/lib/ernie.rb:140:in `start'
/var/lib/gems/1.8/gems/ernie-1.3.0/lib/ernie.rb:128:in `loop'
/var/lib/gems/1.8/gems/ernie-1.3.0/lib/ernie.rb:128:in `start'
/var/lib/gems/1.8/gems/ernie-1.3.0/lib/ernie.rb:209
/data/github/current/ernie/smoke.rb:118
```

Patch:

http://github.com/rtomayko/grit/commit/no_tree

**Comment by defunkt** [comment]
Merged into master.
